/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xform_recipe_mobile_InputPreprocessing */

#ifndef _Included_com_xform_recipe_mobile_InputPreprocessing
#define _Included_com_xform_recipe_mobile_InputPreprocessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xform_recipe_mobile_InputPreprocessing
 * Method:    initRecipeState
 * Signature: (Landroid/graphics/Bitmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_xform_recipe_1mobile_InputPreprocessing_initRecipeState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_xform_recipe_mobile_InputPreprocessing
 * Method:    preprocessInput
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_xform_recipe_1mobile_InputPreprocessing_preprocessInput
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
