/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xform_recipe_mobile_Precomputation */

#ifndef _Included_com_xform_recipe_mobile_Precomputation
#define _Included_com_xform_recipe_mobile_Precomputation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xform_recipe_mobile_Precomputation
 * Method:    precomputeFeatures
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_xform_recipe_1mobile_Precomputation_precomputeFeatures
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
