/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xform_recipe_mobile_RecipeMobile */

#ifndef _Included_com_xform_recipe_mobile_RecipeMobile
#define _Included_com_xform_recipe_mobile_RecipeMobile
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xform_recipe_mobile_RecipeMobile_BIND_ABOVE_CLIENT
#define com_xform_recipe_mobile_RecipeMobile_BIND_ABOVE_CLIENT 8L
#undef com_xform_recipe_mobile_RecipeMobile_BIND_ADJUST_WITH_ACTIVITY
#define com_xform_recipe_mobile_RecipeMobile_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_xform_recipe_mobile_RecipeMobile_BIND_ALLOW_OOM_MANAGEMENT
#define com_xform_recipe_mobile_RecipeMobile_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_xform_recipe_mobile_RecipeMobile_BIND_AUTO_CREATE
#define com_xform_recipe_mobile_RecipeMobile_BIND_AUTO_CREATE 1L
#undef com_xform_recipe_mobile_RecipeMobile_BIND_DEBUG_UNBIND
#define com_xform_recipe_mobile_RecipeMobile_BIND_DEBUG_UNBIND 2L
#undef com_xform_recipe_mobile_RecipeMobile_BIND_IMPORTANT
#define com_xform_recipe_mobile_RecipeMobile_BIND_IMPORTANT 64L
#undef com_xform_recipe_mobile_RecipeMobile_BIND_NOT_FOREGROUND
#define com_xform_recipe_mobile_RecipeMobile_BIND_NOT_FOREGROUND 4L
#undef com_xform_recipe_mobile_RecipeMobile_BIND_WAIVE_PRIORITY
#define com_xform_recipe_mobile_RecipeMobile_BIND_WAIVE_PRIORITY 32L
#undef com_xform_recipe_mobile_RecipeMobile_CONTEXT_IGNORE_SECURITY
#define com_xform_recipe_mobile_RecipeMobile_CONTEXT_IGNORE_SECURITY 2L
#undef com_xform_recipe_mobile_RecipeMobile_CONTEXT_INCLUDE_CODE
#define com_xform_recipe_mobile_RecipeMobile_CONTEXT_INCLUDE_CODE 1L
#undef com_xform_recipe_mobile_RecipeMobile_CONTEXT_RESTRICTED
#define com_xform_recipe_mobile_RecipeMobile_CONTEXT_RESTRICTED 4L
#undef com_xform_recipe_mobile_RecipeMobile_MODE_APPEND
#define com_xform_recipe_mobile_RecipeMobile_MODE_APPEND 32768L
#undef com_xform_recipe_mobile_RecipeMobile_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_xform_recipe_mobile_RecipeMobile_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_xform_recipe_mobile_RecipeMobile_MODE_MULTI_PROCESS
#define com_xform_recipe_mobile_RecipeMobile_MODE_MULTI_PROCESS 4L
#undef com_xform_recipe_mobile_RecipeMobile_MODE_PRIVATE
#define com_xform_recipe_mobile_RecipeMobile_MODE_PRIVATE 0L
#undef com_xform_recipe_mobile_RecipeMobile_MODE_WORLD_READABLE
#define com_xform_recipe_mobile_RecipeMobile_MODE_WORLD_READABLE 1L
#undef com_xform_recipe_mobile_RecipeMobile_MODE_WORLD_WRITEABLE
#define com_xform_recipe_mobile_RecipeMobile_MODE_WORLD_WRITEABLE 2L
#undef com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_DIALER
#define com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_DIALER 1L
#undef com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_DISABLE
#define com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_DISABLE 0L
#undef com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_SEARCH_LOCAL
#define com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_SHORTCUT
#define com_xform_recipe_mobile_RecipeMobile_DEFAULT_KEYS_SHORTCUT 2L
#undef com_xform_recipe_mobile_RecipeMobile_RESULT_CANCELED
#define com_xform_recipe_mobile_RecipeMobile_RESULT_CANCELED 0L
#undef com_xform_recipe_mobile_RecipeMobile_RESULT_FIRST_USER
#define com_xform_recipe_mobile_RecipeMobile_RESULT_FIRST_USER 1L
#undef com_xform_recipe_mobile_RecipeMobile_RESULT_OK
#define com_xform_recipe_mobile_RecipeMobile_RESULT_OK -1L
/*
 * Class:     com_xform_recipe_mobile_RecipeMobile
 * Method:    filterLocalLaplacian
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;IF)V
 */
JNIEXPORT void JNICALL Java_com_xform_recipe_1mobile_RecipeMobile_filterLocalLaplacian
  (JNIEnv *, jobject, jobject, jobject, jint, jfloat);

/*
 * Class:     com_xform_recipe_mobile_RecipeMobile
 * Method:    filterStyleTransfer
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;II)V
 */
JNIEXPORT void JNICALL Java_com_xform_recipe_1mobile_RecipeMobile_filterStyleTransfer
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_xform_recipe_mobile_RecipeMobile
 * Method:    filterColorization
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_xform_recipe_1mobile_RecipeMobile_filterColorization
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_xform_recipe_mobile_RecipeMobile
 * Method:    recipeReconstruct
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[FLandroid/graphics/Bitmap;J)V
 */
JNIEXPORT void JNICALL Java_com_xform_recipe_1mobile_RecipeMobile_recipeReconstruct
  (JNIEnv *, jobject, jobject, jobject, jfloatArray, jobject, jlong);

/*
 * Class:     com_xform_recipe_mobile_RecipeMobile
 * Method:    destroyRecipeState
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_xform_recipe_1mobile_RecipeMobile_destroyRecipeState
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
